### ISSUE TITLE
Can you update this to work with latest version of Hapi v17?

### ISSUE THREAD

**Issue by jrutter** [Belar/hapi-vue#3]

**Comment by Belar** [comment]
Hi, 
the template has been updated to Hapi 17.x. Checked and it seems to be working without issues with 17.2.0 (the most recent version), did you run into any?

**Comment by jrutter** [comment]
I tried to run it and got this:

async function initWebpackTools (middleware, config) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[14:35:55] [nodemon] app crashed - waiting for file changes before starting...

**Comment by Belar** [comment]
Which Node.js version (`node -v`) are you running it in? Async requires Node.js 8 (current LTS; or later) to work out of the box.

**Comment by Belar** [comment]
Closing due to inactivity.
